# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-17 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='name',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='What is Your Name ', max_length=50, unique=True),
        ),
    ]
