# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-10 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mode',
            name='name',
            field=models.CharField(help_text='Please Enter your Desired Mode', max_length=50),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(help_text='Please Enter your Desired State', max_length=50),
        ),
    ]
