# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-12 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20180109_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='mode',
            name='coffee',
            field=models.CharField(default='black', help_text='Please Enter your Desired Mode', max_length=50),
        ),
    ]
