# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-12 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_mode_coffee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffee', models.CharField(help_text='Please Enter your Desired Mode', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='mode',
            name='coffee',
        ),
    ]
