# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-12 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_mode_coffee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mode',
            name='name',
            field=models.IntegerField(help_text='Please Enter a Number'),
        ),
    ]
