# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-12 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20180112_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='mode',
            name='run',
            field=models.IntegerField(default=0, help_text='Please Enter a Number'),
        ),
        migrations.AlterField(
            model_name='mode',
            name='name',
            field=models.CharField(help_text='Please Enter your Desired Mode', max_length=50),
        ),
    ]
