# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-12 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20180112_1339'),
    ]

    operations = [
        migrations.DeleteModel(
            name='State',
        ),
        migrations.DeleteModel(
            name='Style',
        ),
        migrations.RemoveField(
            model_name='mode',
            name='coffee',
        ),
        migrations.RemoveField(
            model_name='mode',
            name='name',
        ),
        migrations.AddField(
            model_name='mode',
            name='mode',
            field=models.CharField(default='manual', help_text='Please Enter your Desired Mode', max_length=50),
        ),
        migrations.AddField(
            model_name='mode',
            name='state',
            field=models.CharField(default='off', help_text='Please Enter your Desired Mode', max_length=50),
        ),
    ]
