# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-12 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20180112_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mode',
            name='run',
            field=models.IntegerField(default=1, help_text='Please Enter a Number'),
        ),
    ]
