# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-12 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20180112_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mode',
            name='state',
            field=models.CharField(default='smdeaf', help_text='Please Enter your Desired Mode', max_length=50),
        ),
    ]
