# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-12 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20180112_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='mode',
            name='name',
            field=models.CharField(default='Austin', help_text='What is Your Name', max_length=50),
        ),
    ]
