# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-16 16:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0012_mode_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(help_text='What is Your Name', max_length=50)),
                ('milk', models.CharField(default='No', help_text='Do you want Milk', max_length=50)),
                ('sugar', models.CharField(default='Yes', help_text='Do you want sugar', max_length=50)),
                ('run', models.IntegerField(default=1, help_text='Please Enter a Number')),
                ('user', models.OneToOneField(help_text='What is Your Name', max_length=50, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Mode',
        ),
    ]
